/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/compare": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Compare
     * @description Same indicateur/groupe across several sources. `sources` = CSV list.
     *
     *     Each returned series keeps its own Convention; never merged (jalon 5, ADR
     *     0003). A source still spanning more than one Convention surfaces the same
     *     422 "pick a Convention" contract as /api/series.
     *
     *     `sources` is a free-form CSV (not a closed Literal like /api/series'
     *     `source`), so it is validated here: an unknown source is a client error and
     *     422s the whole request — consistent with the closed `source` Literal on
     *     /api/series and /api/export.csv, never a silently-degenerate 200.
     */
    get: operations["compare_api_compare_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/export.csv": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Export Csv
     * @description Stream the resolved tidy rows as CSV (jalon 9).
     *
     *     Reuses the jalon-3 resolver (`resolve_rows`), so the export is exactly the
     *     rows the chart was drawn from — same Convention guard, same single-Millésime
     *     pick, same 422 "pick a Convention" contract (handled centrally).
     */
    get: operations["export_csv_api_export_csv_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_api_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/meta": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Meta */
    get: operations["meta_api_meta_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/observations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Observations
     * @description The matching tidy Observation rows, returned VERBATIM and self-describing.
     *
     *     The faithful, unpinned agent access surface (ADR 0004): unlike /api/series,
     *     it NEVER resolves to one Convention and NEVER 422s on ambiguity — co-locating
     *     labelled rows across Conventions is not merging. All filters are optional,
     *     multi-value comma-lists selecting the union; an omitted filter is
     *     unconstrained. All matching Millésimes are returned (Révisions inline, not
     *     deduped); both nominal and euros_constants rows unless narrowed. An empty
     *     match is a normal 200 with []. `total` is the full matched count (truncation
     *     detection) while `limit`/`offset` slice the page.
     */
    get: operations["observations_api_observations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/revisions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Revisions */
    get: operations["revisions_api_revisions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/schema": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Schema
     * @description The machine-readable contract / agent entry point (ADR 0004): the
     *     Conventions, the per-indicateur value semantics with the `dimensionless` flag
     *     (in-band ADR 0003), the known Ruptures, the historisation key, and the guard
     *     rails as English strings. Read-only, public, GET-only.
     */
    get: operations["schema_api_schema_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/series": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Series
     * @description One Convention-pinned, single-Millésime series (ADR 0002).
     *
     *     `concept` is part of the required contract (the frontend always sends it);
     *     the backend additionally guards: if filters still span more than one
     *     Convention, it returns 422 with the available choices rather than merging
     *     (handled centrally by `_ambiguous_convention`).
     */
    get: operations["series_api_series_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/sources": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Sources
     * @description Provenance + licence/attribution per Source (jalon 8; data in `data.py` `SOURCE_INFO`).
     */
    get: operations["sources_api_sources_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AmbiguousConventionDetail
     * @description The `422` body when filters still span more than one Convention (ADR 0002).
     *
     *     Wraps the choices the caller can pin. `error` is a closed literal so the
     *     frontend can branch on it. The `@app.exception_handler` in `main.py` produces
     *     this body at runtime under a `{"detail": …}` envelope; declaring the model via
     *     `responses={422: {"model": AmbiguousConventionDetail}}` only makes it visible
     *     to OpenAPI (and thus generated for the frontend).
     */
    AmbiguousConventionDetail: {
      /** Choices */
      choices: components["schemas"]["ConventionChoice"][];
      /**
       * Error
       * @default ambiguous_convention
       * @constant
       */
      error: "ambiguous_convention";
    };
    /**
     * ConventionChoice
     * @description One Convention the caller may pin to resolve a 422 (ADR 0002). `unite` is
     *     closed; `concept_patrimoine` stays an OPEN string (ADR 0005).
     */
    ConventionChoice: {
      /** Concept Patrimoine */
      concept_patrimoine: string;
      /** Unite */
      unite: string;
    };
    /**
     * ConventionGroup
     * @description The Conventions one Source carries: its single `unite` and the Concepts it
     *     spans (one per Concept — e.g. DGFiP `total`/`immobilier` across the 2018
     *     Rupture). The Convention guard rail forbids comparing across these (CONTEXT.md).
     */
    ConventionGroup: {
      /** Concepts */
      concepts: string[];
      /**
       * Source
       * @enum {string}
       */
      source: "WID" | "INSEE" | "DGFiP";
      /**
       * Unite
       * @enum {string}
       */
      unite: "adulte" | "menage" | "foyer_fiscal";
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * IndicateurSemantics
     * @description Per-`indicateur` value semantics: its `unite_valeur` and whether it is
     *     `dimensionless`. The in-band encoding of ADR 0003 — `%`/`indice` are
     *     dimensionless (cross-source-comparable in *shape*); `euros*` are levels and
     *     `effectif` is a count (both NOT dimensionless, never overlaid across Sources).
     */
    IndicateurSemantics: {
      /** Dimensionless */
      dimensionless: boolean;
      /**
       * Indicateur
       * @enum {string}
       */
      indicateur:
        | "part_patrimoine"
        | "gini"
        | "patrimoine_moyen"
        | "seuil"
        | "nb_foyers"
        | "impot_moyen";
      /** Unites Valeur */
      unites_valeur: string[];
    };
    /**
     * Meta
     * @description Lists of available values, to drive first-level UI filters.
     */
    Meta: {
      /** Annee Max */
      annee_max: number;
      /** Annee Min */
      annee_min: number;
      /** Availability */
      availability: {
        [key: string]: {
          [key: string]: string[];
        };
      };
      /** Concepts */
      concepts: string[];
      /** Groupes */
      groupes: string[];
      /** Indicateurs */
      indicateurs: (
        | "part_patrimoine"
        | "gini"
        | "patrimoine_moyen"
        | "seuil"
        | "nb_foyers"
        | "impot_moyen"
      )[];
      /** Millesimes */
      millesimes: string[];
      /** Sources */
      sources: ("WID" | "INSEE" | "DGFiP")[];
      /** Tranche Taux */
      tranche_taux: {
        [key: string]: number;
      };
      /** Unites */
      unites: ("adulte" | "menage" | "foyer_fiscal")[];
    };
    /**
     * Observation
     * @description One tidy Observation row, returned VERBATIM and self-describing — the
     *     `EXPORT_COLUMNS` shape (CONTEXT.md tidy schema). Every row carries its own
     *     Convention (`unite` + `concept_patrimoine`) and traceability (`source`,
     *     `millesime_source`, `date_extraction`), so co-locating rows from several
     *     Conventions is never merging (ADR 0004).
     */
    Observation: {
      /** Annee */
      annee: number;
      /** Concept Patrimoine */
      concept_patrimoine: string;
      /** Date Extraction */
      date_extraction: string;
      /** Euros Constants */
      euros_constants: boolean;
      /** Groupe */
      groupe: string;
      /**
       * Indicateur
       * @enum {string}
       */
      indicateur:
        | "part_patrimoine"
        | "gini"
        | "patrimoine_moyen"
        | "seuil"
        | "nb_foyers"
        | "impot_moyen";
      /** Millesime Source */
      millesime_source: string;
      /** Notes */
      notes?: string | null;
      /**
       * Source
       * @enum {string}
       */
      source: "WID" | "INSEE" | "DGFiP";
      /**
       * Unite
       * @enum {string}
       */
      unite: "adulte" | "menage" | "foyer_fiscal";
      /** Unite Valeur */
      unite_valeur: string;
      /** Valeur */
      valeur: number;
    };
    /**
     * ObservationsResponse
     * @description Response for GET /api/observations — matching rows co-located, never merged.
     *
     *     `query` echoes the resolved filters; `total` is the full matched count (so a
     *     consumer can detect truncation against `limit`); `observations` is the
     *     `limit`/`offset` page. Never resolves to one Convention and never 422s on
     *     ambiguity (ADR 0004).
     */
    ObservationsResponse: {
      /** Limit */
      limit: number;
      /** Observations */
      observations: components["schemas"]["Observation"][];
      /** Offset */
      offset: number;
      /** Query */
      query: {
        [key: string]: unknown;
      };
      /** Total */
      total: number;
    };
    /** Point */
    Point: {
      /** Annee */
      annee: number;
      /** Valeur */
      valeur: number;
    };
    /**
     * RevisionDiff
     * @description An observation that exists in more than one millésime (`/api/revisions`).
     */
    RevisionDiff: {
      /** Annee */
      annee: number;
      /** Concept Patrimoine */
      concept_patrimoine: string;
      /** Groupe */
      groupe: string;
      /**
       * Indicateur
       * @enum {string}
       */
      indicateur:
        | "part_patrimoine"
        | "gini"
        | "patrimoine_moyen"
        | "seuil"
        | "nb_foyers"
        | "impot_moyen";
      /**
       * Source
       * @enum {string}
       */
      source: "WID" | "INSEE" | "DGFiP";
      /**
       * Unite
       * @enum {string}
       */
      unite: "adulte" | "menage" | "foyer_fiscal";
      /** Valeurs */
      valeurs: components["schemas"]["RevisionValeur"][];
    };
    /**
     * RevisionValeur
     * @description One competing Millésime of a revised Observation: its value and the
     *     `date_extraction` that orders the révision (append-only historisation).
     */
    RevisionValeur: {
      /** Date Extraction */
      date_extraction: string;
      /** Millesime Source */
      millesime_source: string;
      /** Valeur */
      valeur: number;
    };
    /**
     * Rupture
     * @description A methodological break to annotate on a series (e.g. 2018 ISF->IFI).
     */
    Rupture: {
      /** Annee */
      annee: number;
      /** Label */
      label: string;
    };
    /**
     * Schema
     * @description Response for GET /api/schema — the machine-readable contract / agent entry
     *     point (ADR 0004). Lets an agent learn the Conventions, the per-indicateur
     *     value semantics with the `dimensionless` flag, the known Ruptures, the
     *     historisation key, and the guard rails (as English strings) from the API
     *     itself rather than only from CONTEXT.md out-of-band.
     */
    Schema: {
      /** Conventions */
      conventions: components["schemas"]["ConventionGroup"][];
      /** Historisation Key */
      historisation_key: string[];
      /** Indicateurs */
      indicateurs: components["schemas"]["IndicateurSemantics"][];
      /** Rules */
      rules: string[];
      /** Ruptures */
      ruptures: components["schemas"]["SchemaRupture"][];
    };
    /**
     * SchemaRupture
     * @description A known methodological break, with its Source, for /api/schema (e.g. the
     *     DGFiP 2018 ISF→IFI Rupture). Unlike `Rupture`, it names the Source it belongs
     *     to so an agent can attribute the break.
     */
    SchemaRupture: {
      /** Annee */
      annee: number;
      /** Label */
      label: string;
      /**
       * Source
       * @enum {string}
       */
      source: "WID" | "INSEE" | "DGFiP";
    };
    /**
     * Series
     * @description Response for GET /api/series — a single filtered series.
     *
     *     `unite` and `concept_patrimoine` are echoed back because they qualify the
     *     meaning of every value (the Convention). Never drop them.
     */
    Series: {
      /** Concept Patrimoine */
      concept_patrimoine: string;
      /**
       * Date Extraction
       * @default
       */
      date_extraction: string;
      /** Millesime Source */
      millesime_source: string;
      /** Points */
      points: components["schemas"]["Point"][];
      /** Query */
      query: {
        [key: string]: unknown;
      };
      /**
       * Ruptures
       * @default []
       */
      ruptures: components["schemas"]["Rupture"][];
      /**
       * Unite
       * @enum {string}
       */
      unite: "adulte" | "menage" | "foyer_fiscal";
      /** Unite Valeur */
      unite_valeur: string;
    };
    /**
     * SourceInfo
     * @description Provenance + licence/attribution metadata (data in `data.py` `SOURCE_INFO`, served by `/api/sources`).
     */
    SourceInfo: {
      /** Attribution */
      attribution: string;
      /** Convention */
      convention: string;
      /** Licence */
      licence: string;
      /**
       * Source
       * @enum {string}
       */
      source: "WID" | "INSEE" | "DGFiP";
      /** Url */
      url: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type AmbiguousConventionDetail = components["schemas"]["AmbiguousConventionDetail"];
export type ConventionChoice = components["schemas"]["ConventionChoice"];
export type ConventionGroup = components["schemas"]["ConventionGroup"];
export type HttpValidationError = components["schemas"]["HTTPValidationError"];
export type IndicateurSemantics = components["schemas"]["IndicateurSemantics"];
export type Meta = components["schemas"]["Meta"];
export type Observation = components["schemas"]["Observation"];
export type ObservationsResponse = components["schemas"]["ObservationsResponse"];
export type Point = components["schemas"]["Point"];
export type RevisionDiff = components["schemas"]["RevisionDiff"];
export type RevisionValeur = components["schemas"]["RevisionValeur"];
export type Rupture = components["schemas"]["Rupture"];
export type Schema = components["schemas"]["Schema"];
export type SchemaRupture = components["schemas"]["SchemaRupture"];
export type Series = components["schemas"]["Series"];
export type SourceInfo = components["schemas"]["SourceInfo"];
export type ValidationError = components["schemas"]["ValidationError"];
export type $defs = Record<string, never>;
export interface operations {
  compare_api_compare_get: {
    parameters: {
      query: {
        indicateur:
          | "part_patrimoine"
          | "gini"
          | "patrimoine_moyen"
          | "seuil"
          | "nb_foyers"
          | "impot_moyen";
        groupe: string;
        sources: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Series"][];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AmbiguousConventionDetail"];
        };
      };
    };
  };
  export_csv_api_export_csv_get: {
    parameters: {
      query: {
        source: "WID" | "INSEE" | "DGFiP";
        indicateur:
          | "part_patrimoine"
          | "gini"
          | "patrimoine_moyen"
          | "seuil"
          | "nb_foyers"
          | "impot_moyen";
        groupe: string;
        concept?: string | null;
        unite?: ("adulte" | "menage" | "foyer_fiscal") | null;
        annee_min?: number;
        annee_max?: number | null;
        euros_constants?: boolean;
        millesime?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AmbiguousConventionDetail"];
        };
      };
    };
  };
  health_api_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  meta_api_meta_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Meta"];
        };
      };
    };
  };
  observations_api_observations_get: {
    parameters: {
      query?: {
        source?: string | null;
        indicateur?: string | null;
        groupe?: string | null;
        concept?: string | null;
        unite?: string | null;
        millesime?: string | null;
        annee_min?: number;
        annee_max?: number | null;
        euros_constants?: boolean | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ObservationsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  revisions_api_revisions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevisionDiff"][];
        };
      };
    };
  };
  schema_api_schema_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Schema"];
        };
      };
    };
  };
  series_api_series_get: {
    parameters: {
      query: {
        source: "WID" | "INSEE" | "DGFiP";
        indicateur:
          | "part_patrimoine"
          | "gini"
          | "patrimoine_moyen"
          | "seuil"
          | "nb_foyers"
          | "impot_moyen";
        groupe: string;
        concept?: string | null;
        unite?: ("adulte" | "menage" | "foyer_fiscal") | null;
        annee_min?: number;
        annee_max?: number | null;
        euros_constants?: boolean;
        millesime?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Series"];
        };
      };
      /** @description Unprocessable Content */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AmbiguousConventionDetail"];
        };
      };
    };
  };
  sources_api_sources_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SourceInfo"][];
        };
      };
    };
  };
}
